SUPABASE_URL = "https://plvpywtnuwroxoarqjmz.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBsdnB5d3RudXdyb3hvYXJxam16Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODU5NzkzNjQsImV4cCI6MjEwMTU1NTM2NH0.DT53diNUKJv-yYgIFH829l7jyjYIZsbYAeaPmi87MDE"
